name: Lint
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        container:
            image: node:14
            env:
                NODE_ENV: development
        steps:
            -
                name: Checkout ğŸ›ï¸
                uses: actions/checkout@v2.3.1
                with:
                    persist-credentials: false

            -
                name: Install
                run: yarn install

            -
                name: Lint
                run: yarn lint

#            -
#                name: Test
#                run: yarn test
